Add homoglyphs rule types
stacklok/minder-rules-and-profiles pull request #51
Opened 2024-02-09 19:24 UTC by teodor-yanev

2024-02-23 09:24 UTC, jhrozek reviewed
could we add links that describe what kind of attack this prevents? I don't think they are very well known

2024-02-26 11:19 UTC, JAORMX requested changes

2024-02-26 11:19 UTC, JAORMX commented on rule-types/github/homoglyphs_invisible_characters.yaml
> +  fail and the pull request will be commented on.
The guidance is meant to tell you what to do if the rule fails. This is more appropriate for a description.

2024-02-26 11:19 UTC, JAORMX commented on rule-types/github/homoglyphs_mixed_scripts.yaml
> +  fail and the pull request will be commented on.
The guidance is meant to tell you what to do if the rule fails. This is more appropriate for a description.

2024-02-26 17:20 UTC, teodor-yanev commented on rule-types/github/homoglyphs_mixed_scripts.yaml
> +  fail and the pull request will be commented on.
Thanks: updated

2024-02-26 17:25 UTC, JAORMX approved these changes

2024-02-26 17:25 UTC, merged